name: playwright
on:
  workflow_dispatch: # allows you to run this workflow manually from the Actions tab
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install chromium --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - name: Publish results
      if: ${{ always() }}
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add test-results
        tag="$(date +%s)"
        git commit -m "latest change: $(date -u)" -m "view trace:https://trace.playwright.dev/?trace=https://raw.githubusercontent.com/felixlohmeier/playwright-github-action/refs/tags/${tag}/test-results/example-get-started-link-desktop/trace.zip" || exit 0
        git tag "$tag"
        git push
        git push --tags
